class_name ActorType

enum ActorType {
	PLAYER						= 0
	ENEMY_MELEE_BASIC			= 1
	ENEMY_MELEE_FAST			= 2
	ENEMY_RANGED_BASIC			= 3
	ENEMY_RANGED_ADVANCED		= 4
	ENEMY_TANK					= 5
	PROJECTILE_PLAYER_BULLET	= 6
	PROJECTILE_PLAYER_HARPOON	= 7
	PROJECTILE_ENEMY_BULLET		= 8
	PROJECTILE_ENEMY_HARPOON	= 9
}
